bin = 'USBCopyer.Release.exe'
checkver = 'github'
description = 'ğŸ˜‰ ç”¨äºåœ¨æ’ä¸ŠUç›˜åè‡ªåŠ¨æŒ‰éœ€å¤åˆ¶è¯¥Uç›˜çš„æ–‡ä»¶ã€‚â€å¤‡ä»½&å·Uç›˜æ–‡ä»¶çš„ç¥å™¨â€ï¼ˆå†™ä½œUSBCopyerï¼Œè¯»ä½œUSBCopierï¼‰ https://kenvix.com/post/usbcopyer/'
hash = 'F032C10A61E2E24A422308B88908A39BC9172F9EFA78B4E6879E3BAF7C70C233'
homepage = 'https://github.com/kenvix/USBCopyer'
license = 'GPL-3.0'
persist = [ 'USBCopyerData' ]
shortcuts = [ [ 'USBCopyer.Release.exe', 'USBCopyer' ] ]
url = 'https://github.com/kenvix/USBCopyer/releases/download/V5.11/USBCopyer.Release.exe'
version = '5.11'

[autoupdate]
url = 'https://github.com/kenvix/USBCopyer/releases/download/V$version/USBCopyer.Release.exe'